version: '3.4'

services:
  exportarr:
    container_name: exportarr
    image: petersem/exportarr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      TOKEN: "xyzzy"
      RADARR_URL: "http://radarrhost:7878"
      RADARR_TOKEN: "your radarr token"
      SONARR_URL: "http://sonarrhost:8989"
      SONARR_TOKEN: "your sonarr token"
    ports:
      - 1234:3000
