version: '3.4'

services:
  exportarr:
    container_name: exportarr
    image: petersem/exportarr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      TOKEN: "xyzzy"
      RADARR_URL: "http://192.168.1.135:7878"
      RADARR_TOKEN: "yourradarrtoken"
      SONARR_URL: "http://192.168.1.135:8989"
      SONARR_TOKEN: "yoursonarrtoken"
      SONARR_BETA: "true"
    ports:
      - 1234:3000
